INSERT INTO products (code, name, description, image_url, price) VALUES
('B001', 'The Great Gatsby', 'Classic novel by F. Scott Fitzgerald', 'https://example.com/books/gatsby.jpg', 399.00),
('B002', '1984', 'Dystopian novel by George Orwell', 'https://example.com/books/1984.jpg', 299.50),
('B003', 'To Kill a Mockingbird', 'Pulitzer Prize-winning novel by Harper Lee', 'https://example.com/books/mockingbird.jpg', 349.75),
('B004', 'Pride and Prejudice', 'Romantic novel by Jane Austen', 'https://example.com/books/pride.jpg', 279.90),
('B005', 'The Catcher in the Rye', 'Controversial novel by J.D. Salinger', 'https://example.com/books/catcher.jpg', 319.25),
('B006', 'The Alchemist', 'Inspirational tale by Paulo Coelho', 'https://example.com/books/alchemist.jpg', 250.00),
('B007', 'Sapiens', 'A Brief History of Humankind by Yuval Noah Harari', 'https://example.com/books/sapiens.jpg', 499.00),
('B008', 'Becoming', 'Memoir by Michelle Obama', 'https://example.com/books/becoming.jpg', 599.99),
('B009', 'Harry Potter and the Sorcerer''s Stone', 'Fantasy novel by J.K. Rowling', 'https://example.com/books/hp1.jpg', 699.00),
('B010', 'The Hobbit', 'Fantasy novel by J.R.R. Tolkien', 'https://example.com/books/hobbit.jpg', 649.00),
('B011', 'The Power of Habit', 'Self-help book by Charles Duhigg', 'https://example.com/books/habit.jpg', 399.50),
('B012', 'Atomic Habits', 'Tiny changes for remarkable results by James Clear', 'https://example.com/books/atomic.jpg', 449.00),
('B013', 'The Subtle Art of Not Giving a F*ck', 'Counterintuitive approach by Mark Manson', 'https://example.com/books/subtleart.jpg', 399.99),
('B014', 'Deep Work', 'Focused success in a distracted world by Cal Newport', 'https://example.com/books/deepwork.jpg', 429.00),
('B015', 'Thinking, Fast and Slow', 'Psychological insights by Daniel Kahneman', 'https://example.com/books/thinking.jpg', 499.75);
